version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ="Europe/Istanbul"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  oap:
    image: apache/skywalking-oap-server:8.0.1-es7
    container_name: oap
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      TZ: "Europe/Istanbul"
  ui:
    image: apache/skywalking-ui:8.0.1
    container_name: ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 1080:8080
    environment:
      SW_OAP_ADDRESS: oap:12800
      TZ: "Europe/Istanbul"
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      TZ: "Europe/Istanbul"      


  service-a:
    image: service-a
    depends_on:
      - oap
    links:
      - oap
    ports:
      - 9090:9090
    environment:
      TZ: "Europe/Istanbul"

  service-b:
    image: service-b
    depends_on:
      - oap    
    links:
      - oap
      - mongodb
    ports:
      - 8090:8090
    environment:
      TZ: "Europe/Istanbul"        